from enum import Enum

class RiskSeverity(str, Enum):
    CRITICAL = "CRITICAL"
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"
    INFORMATIONAL = "INFORMATIONAL"

class TriggerType(str, Enum):
    MAINTENANCE_RECORD_UPLOADED = "MAINTENANCE_RECORD_UPLOADED"
    INSPECTION_REPORT_UPLOADED = "INSPECTION_REPORT_UPLOADED"
    INCIDENT_REPORT_UPLOADED = "INCIDENT_REPORT_UPLOADED"
    EQUIPMENT_MANUAL_UPDATED = "EQUIPMENT_MANUAL_UPDATED"
    SCHEDULED_SCAN = "SCHEDULED_SCAN"
    MANUAL_SCAN = "MANUAL_SCAN"

class FindingStatus(str, Enum):
    OPEN = "OPEN"
    UNDER_REVIEW = "UNDER_REVIEW"
    SCHEDULED = "SCHEDULED"
    RESOLVED = "RESOLVED"
    DISMISSED = "DISMISSED"

class FailureCategory(str, Enum):
    MECHANICAL_DEGRADATION = "MECHANICAL_DEGRADATION"
    THERMAL_STRESS = "THERMAL_STRESS"
    ELECTRICAL_FAULT = "ELECTRICAL_FAULT"
    CAVITATION_CORROSION = "CAVITATION_CORROSION"
    MISSED_PREVENTIVE_WINDOW = "MISSED_PREVENTIVE_WINDOW"
    OPERATIONAL_ANOMALY = "OPERATIONAL_ANOMALY"
